# Generated by Django 2.2.2 on 2019-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.URLField()),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'tb_usuario',
            },
        ),
    ]
