# Generated by Django 2.2.2 on 2019-06-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190612_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagem',
            new_name='foto',
        ),
    ]
