# Generated by Django 2.2.2 on 2019-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tempo', models.IntegerField(max_length=2)),
                ('icone', models.URLField(max_length=255)),
                ('criado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_servico',
            },
        ),
    ]
