# Generated by Django 2.2.2 on 2019-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
