# Generated by Django 2.2.2 on 2019-06-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario_agendado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioagendado',
            name='horario',
            field=models.ForeignKey(db_column='horario', on_delete=django.db.models.deletion.PROTECT, to='horario.Horario'),
        ),
        migrations.AlterField(
            model_name='horarioagendado',
            name='servico',
            field=models.ForeignKey(db_column='servico', on_delete=django.db.models.deletion.PROTECT, to='servico.Servico'),
        ),
        migrations.AlterField(
            model_name='horarioagendado',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
        ),
    ]
