# Generated by Django 2.2.2 on 2019-06-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario_agendado', '0002_auto_20190612_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioagendado',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='horario.Horario'),
        ),
        migrations.AlterField(
            model_name='horarioagendado',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.Servico'),
        ),
        migrations.AlterField(
            model_name='horarioagendado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
        ),
    ]
