# Generated by Django 2.2.2 on 2019-06-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario_agendado', '0003_auto_20190612_1959'),
        ('horario_agendado', '0002_auto_20190612_1629'),
    ]

    operations = [
    ]
